version: 1.2
workflows:
   - subclass: cwl
     primaryDescriptorPath: /Dockstore.cwl
     testParameterFiles:
         - /test/dockstore.cwl.json
            -this fails
         foobar:
     name: foobar2
